monolog:
    channels:
        - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists

when@dev:
    monolog:
        handlers:
            security:
                level: debug
                type: rotating_file
                max_files: 10
                path: '%kernel.logs_dir%/security.%kernel.environment%.log'
                channels:
                    - "security"
            main:
                type: rotating_file
                max_files: 10
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                channels: 
                    - "!event"
                    - "!security"
                    - "!doctrine"
                    - "!request"
                    - "!deprecation"
            doctrine:
                level: debug
                type: rotating_file
                max_files: 10
                path: '%kernel.logs_dir%/doctrine.%kernel.environment%.log'
                channels:
                    - "doctrine"
            request:
                level: debug
                type: rotating_file
                max_files: 10
                path: '%kernel.logs_dir%/request.%kernel.environment%.log'
                channels:
                    - "request"
            deprecation:
                level: debug
                type: rotating_file
                max_files: 10
                path: '%kernel.logs_dir%/deprecation.%kernel.environment%.log'
                channels:
                    - "deprecation"
            # uncomment to get logging in your browser
            # you may have to allow bigger header sizes in your Web server configuration
            #firephp:
            #    type: firephp
            #    level: info
            #chromephp:
            #    type: chromephp
            #    level: info
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!console"]

when@test:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                channels: ["!event"]
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug

when@prod:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                buffer_size: 50 # How many messages should be saved? Prevent memory leaks
            nested:
                type: stream
                path: php://stderr
                level: debug
                formatter: monolog.formatter.json
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine"]
            deprecation:
                type: stream
                channels: [deprecation]
                path: php://stderr
